spring.application.name=job-matching-platform
server.port=8080

# Datasource - MySQL
# spring.datasource.url=jdbc:mysql://localhost:3306/jobmatch?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.url=jdbc:mysql://localhost:3308/jobmatch
spring.datasource.username=root
spring.datasource.password=Ankit@345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_batch_fetch_size=25
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SQL Init
spring.sql.init.mode=never

# Multipart
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# App Config
app.matching.weight-skill=0.6
app.matching.weight-gpa=0.2
app.matching.weight-auth=0.2
app.upload.resume-dir=./uploads/resumes
app.cors.allowed-origin=http://localhost:4200

# JWT
app.jwt.secret=jobmatch-super-secret-key-2024-must-be-at-least-256-bits-long
app.jwt.expiration-ms=86400000
